// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yang/wormhole_backend/internal/dal/model"
)

func newCarouselSlide(db *gorm.DB, opts ...gen.DOOption) carouselSlide {
	_carouselSlide := carouselSlide{}

	_carouselSlide.carouselSlideDo.UseDB(db, opts...)
	_carouselSlide.carouselSlideDo.UseModel(&model.CarouselSlide{})

	tableName := _carouselSlide.carouselSlideDo.TableName()
	_carouselSlide.ALL = field.NewAsterisk(tableName)
	_carouselSlide.ID = field.NewInt64(tableName, "id")
	_carouselSlide.Code = field.NewString(tableName, "code")
	_carouselSlide.Title = field.NewString(tableName, "title")
	_carouselSlide.Subtitle = field.NewString(tableName, "subtitle")
	_carouselSlide.Description = field.NewString(tableName, "description")
	_carouselSlide.ImageURL = field.NewString(tableName, "image_url")
	_carouselSlide.Background = field.NewString(tableName, "background")
	_carouselSlide.ButtonText = field.NewString(tableName, "button_text")
	_carouselSlide.TargetURL = field.NewString(tableName, "target_url")
	_carouselSlide.AutoplaySeconds = field.NewInt32(tableName, "autoplay_seconds")
	_carouselSlide.StartsAt = field.NewTime(tableName, "starts_at")
	_carouselSlide.EndsAt = field.NewTime(tableName, "ends_at")
	_carouselSlide.VisibleRoleCodes = field.NewString(tableName, "visible_role_codes")
	_carouselSlide.SortOrder = field.NewInt32(tableName, "sort_order")
	_carouselSlide.Status = field.NewInt16(tableName, "status")
	_carouselSlide.CreatedBy = field.NewInt64(tableName, "created_by")
	_carouselSlide.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_carouselSlide.CreatedAt = field.NewTime(tableName, "created_at")
	_carouselSlide.UpdatedAt = field.NewTime(tableName, "updated_at")

	_carouselSlide.fillFieldMap()

	return _carouselSlide
}

type carouselSlide struct {
	carouselSlideDo

	ALL              field.Asterisk
	ID               field.Int64
	Code             field.String
	Title            field.String
	Subtitle         field.String
	Description      field.String
	ImageURL         field.String
	Background       field.String
	ButtonText       field.String
	TargetURL        field.String
	AutoplaySeconds  field.Int32
	StartsAt         field.Time
	EndsAt           field.Time
	VisibleRoleCodes field.String
	SortOrder        field.Int32
	Status           field.Int16
	CreatedBy        field.Int64
	UpdatedBy        field.Int64
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (c carouselSlide) Table(newTableName string) *carouselSlide {
	c.carouselSlideDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c carouselSlide) As(alias string) *carouselSlide {
	c.carouselSlideDo.DO = *(c.carouselSlideDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *carouselSlide) updateTableName(table string) *carouselSlide {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.Code = field.NewString(table, "code")
	c.Title = field.NewString(table, "title")
	c.Subtitle = field.NewString(table, "subtitle")
	c.Description = field.NewString(table, "description")
	c.ImageURL = field.NewString(table, "image_url")
	c.Background = field.NewString(table, "background")
	c.ButtonText = field.NewString(table, "button_text")
	c.TargetURL = field.NewString(table, "target_url")
	c.AutoplaySeconds = field.NewInt32(table, "autoplay_seconds")
	c.StartsAt = field.NewTime(table, "starts_at")
	c.EndsAt = field.NewTime(table, "ends_at")
	c.VisibleRoleCodes = field.NewString(table, "visible_role_codes")
	c.SortOrder = field.NewInt32(table, "sort_order")
	c.Status = field.NewInt16(table, "status")
	c.CreatedBy = field.NewInt64(table, "created_by")
	c.UpdatedBy = field.NewInt64(table, "updated_by")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *carouselSlide) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *carouselSlide) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 19)
	c.fieldMap["id"] = c.ID
	c.fieldMap["code"] = c.Code
	c.fieldMap["title"] = c.Title
	c.fieldMap["subtitle"] = c.Subtitle
	c.fieldMap["description"] = c.Description
	c.fieldMap["image_url"] = c.ImageURL
	c.fieldMap["background"] = c.Background
	c.fieldMap["button_text"] = c.ButtonText
	c.fieldMap["target_url"] = c.TargetURL
	c.fieldMap["autoplay_seconds"] = c.AutoplaySeconds
	c.fieldMap["starts_at"] = c.StartsAt
	c.fieldMap["ends_at"] = c.EndsAt
	c.fieldMap["visible_role_codes"] = c.VisibleRoleCodes
	c.fieldMap["sort_order"] = c.SortOrder
	c.fieldMap["status"] = c.Status
	c.fieldMap["created_by"] = c.CreatedBy
	c.fieldMap["updated_by"] = c.UpdatedBy
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c carouselSlide) clone(db *gorm.DB) carouselSlide {
	c.carouselSlideDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c carouselSlide) replaceDB(db *gorm.DB) carouselSlide {
	c.carouselSlideDo.ReplaceDB(db)
	return c
}

type carouselSlideDo struct{ gen.DO }

type ICarouselSlideDo interface {
	gen.SubQuery
	Debug() ICarouselSlideDo
	WithContext(ctx context.Context) ICarouselSlideDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICarouselSlideDo
	WriteDB() ICarouselSlideDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICarouselSlideDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICarouselSlideDo
	Not(conds ...gen.Condition) ICarouselSlideDo
	Or(conds ...gen.Condition) ICarouselSlideDo
	Select(conds ...field.Expr) ICarouselSlideDo
	Where(conds ...gen.Condition) ICarouselSlideDo
	Order(conds ...field.Expr) ICarouselSlideDo
	Distinct(cols ...field.Expr) ICarouselSlideDo
	Omit(cols ...field.Expr) ICarouselSlideDo
	Join(table schema.Tabler, on ...field.Expr) ICarouselSlideDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICarouselSlideDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICarouselSlideDo
	Group(cols ...field.Expr) ICarouselSlideDo
	Having(conds ...gen.Condition) ICarouselSlideDo
	Limit(limit int) ICarouselSlideDo
	Offset(offset int) ICarouselSlideDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICarouselSlideDo
	Unscoped() ICarouselSlideDo
	Create(values ...*model.CarouselSlide) error
	CreateInBatches(values []*model.CarouselSlide, batchSize int) error
	Save(values ...*model.CarouselSlide) error
	First() (*model.CarouselSlide, error)
	Take() (*model.CarouselSlide, error)
	Last() (*model.CarouselSlide, error)
	Find() ([]*model.CarouselSlide, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CarouselSlide, err error)
	FindInBatches(result *[]*model.CarouselSlide, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CarouselSlide) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICarouselSlideDo
	Assign(attrs ...field.AssignExpr) ICarouselSlideDo
	Joins(fields ...field.RelationField) ICarouselSlideDo
	Preload(fields ...field.RelationField) ICarouselSlideDo
	FirstOrInit() (*model.CarouselSlide, error)
	FirstOrCreate() (*model.CarouselSlide, error)
	FindByPage(offset int, limit int) (result []*model.CarouselSlide, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICarouselSlideDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c carouselSlideDo) Debug() ICarouselSlideDo {
	return c.withDO(c.DO.Debug())
}

func (c carouselSlideDo) WithContext(ctx context.Context) ICarouselSlideDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c carouselSlideDo) ReadDB() ICarouselSlideDo {
	return c.Clauses(dbresolver.Read)
}

func (c carouselSlideDo) WriteDB() ICarouselSlideDo {
	return c.Clauses(dbresolver.Write)
}

func (c carouselSlideDo) Session(config *gorm.Session) ICarouselSlideDo {
	return c.withDO(c.DO.Session(config))
}

func (c carouselSlideDo) Clauses(conds ...clause.Expression) ICarouselSlideDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c carouselSlideDo) Returning(value interface{}, columns ...string) ICarouselSlideDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c carouselSlideDo) Not(conds ...gen.Condition) ICarouselSlideDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c carouselSlideDo) Or(conds ...gen.Condition) ICarouselSlideDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c carouselSlideDo) Select(conds ...field.Expr) ICarouselSlideDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c carouselSlideDo) Where(conds ...gen.Condition) ICarouselSlideDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c carouselSlideDo) Order(conds ...field.Expr) ICarouselSlideDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c carouselSlideDo) Distinct(cols ...field.Expr) ICarouselSlideDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c carouselSlideDo) Omit(cols ...field.Expr) ICarouselSlideDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c carouselSlideDo) Join(table schema.Tabler, on ...field.Expr) ICarouselSlideDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c carouselSlideDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICarouselSlideDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c carouselSlideDo) RightJoin(table schema.Tabler, on ...field.Expr) ICarouselSlideDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c carouselSlideDo) Group(cols ...field.Expr) ICarouselSlideDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c carouselSlideDo) Having(conds ...gen.Condition) ICarouselSlideDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c carouselSlideDo) Limit(limit int) ICarouselSlideDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c carouselSlideDo) Offset(offset int) ICarouselSlideDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c carouselSlideDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICarouselSlideDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c carouselSlideDo) Unscoped() ICarouselSlideDo {
	return c.withDO(c.DO.Unscoped())
}

func (c carouselSlideDo) Create(values ...*model.CarouselSlide) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c carouselSlideDo) CreateInBatches(values []*model.CarouselSlide, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c carouselSlideDo) Save(values ...*model.CarouselSlide) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c carouselSlideDo) First() (*model.CarouselSlide, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CarouselSlide), nil
	}
}

func (c carouselSlideDo) Take() (*model.CarouselSlide, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CarouselSlide), nil
	}
}

func (c carouselSlideDo) Last() (*model.CarouselSlide, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CarouselSlide), nil
	}
}

func (c carouselSlideDo) Find() ([]*model.CarouselSlide, error) {
	result, err := c.DO.Find()
	return result.([]*model.CarouselSlide), err
}

func (c carouselSlideDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CarouselSlide, err error) {
	buf := make([]*model.CarouselSlide, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c carouselSlideDo) FindInBatches(result *[]*model.CarouselSlide, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c carouselSlideDo) Attrs(attrs ...field.AssignExpr) ICarouselSlideDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c carouselSlideDo) Assign(attrs ...field.AssignExpr) ICarouselSlideDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c carouselSlideDo) Joins(fields ...field.RelationField) ICarouselSlideDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c carouselSlideDo) Preload(fields ...field.RelationField) ICarouselSlideDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c carouselSlideDo) FirstOrInit() (*model.CarouselSlide, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CarouselSlide), nil
	}
}

func (c carouselSlideDo) FirstOrCreate() (*model.CarouselSlide, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CarouselSlide), nil
	}
}

func (c carouselSlideDo) FindByPage(offset int, limit int) (result []*model.CarouselSlide, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c carouselSlideDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c carouselSlideDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c carouselSlideDo) Delete(models ...*model.CarouselSlide) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *carouselSlideDo) withDO(do gen.Dao) *carouselSlideDo {
	c.DO = *do.(*gen.DO)
	return c
}
