// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yang/wormhole_backend/internal/dal/model"
)

func newQuickEntry(db *gorm.DB, opts ...gen.DOOption) quickEntry {
	_quickEntry := quickEntry{}

	_quickEntry.quickEntryDo.UseDB(db, opts...)
	_quickEntry.quickEntryDo.UseModel(&model.QuickEntry{})

	tableName := _quickEntry.quickEntryDo.TableName()
	_quickEntry.ALL = field.NewAsterisk(tableName)
	_quickEntry.ID = field.NewInt32(tableName, "id")
	_quickEntry.Code = field.NewString(tableName, "code")
	_quickEntry.Title = field.NewString(tableName, "title")
	_quickEntry.IconURL = field.NewString(tableName, "icon_url")
	_quickEntry.IconText = field.NewString(tableName, "icon_text")
	_quickEntry.TargetURL = field.NewString(tableName, "target_url")
	_quickEntry.Description = field.NewString(tableName, "description")
	_quickEntry.VisibleRoleCodes = field.NewString(tableName, "visible_role_codes")
	_quickEntry.SortOrder = field.NewInt32(tableName, "sort_order")
	_quickEntry.Status = field.NewInt16(tableName, "status")
	_quickEntry.CreatedBy = field.NewInt64(tableName, "created_by")
	_quickEntry.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_quickEntry.CreatedAt = field.NewTime(tableName, "created_at")
	_quickEntry.UpdatedAt = field.NewTime(tableName, "updated_at")

	_quickEntry.fillFieldMap()

	return _quickEntry
}

type quickEntry struct {
	quickEntryDo

	ALL              field.Asterisk
	ID               field.Int32
	Code             field.String
	Title            field.String
	IconURL          field.String
	IconText         field.String
	TargetURL        field.String
	Description      field.String
	VisibleRoleCodes field.String
	SortOrder        field.Int32
	Status           field.Int16
	CreatedBy        field.Int64
	UpdatedBy        field.Int64
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (q quickEntry) Table(newTableName string) *quickEntry {
	q.quickEntryDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q quickEntry) As(alias string) *quickEntry {
	q.quickEntryDo.DO = *(q.quickEntryDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *quickEntry) updateTableName(table string) *quickEntry {
	q.ALL = field.NewAsterisk(table)
	q.ID = field.NewInt32(table, "id")
	q.Code = field.NewString(table, "code")
	q.Title = field.NewString(table, "title")
	q.IconURL = field.NewString(table, "icon_url")
	q.IconText = field.NewString(table, "icon_text")
	q.TargetURL = field.NewString(table, "target_url")
	q.Description = field.NewString(table, "description")
	q.VisibleRoleCodes = field.NewString(table, "visible_role_codes")
	q.SortOrder = field.NewInt32(table, "sort_order")
	q.Status = field.NewInt16(table, "status")
	q.CreatedBy = field.NewInt64(table, "created_by")
	q.UpdatedBy = field.NewInt64(table, "updated_by")
	q.CreatedAt = field.NewTime(table, "created_at")
	q.UpdatedAt = field.NewTime(table, "updated_at")

	q.fillFieldMap()

	return q
}

func (q *quickEntry) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *quickEntry) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 14)
	q.fieldMap["id"] = q.ID
	q.fieldMap["code"] = q.Code
	q.fieldMap["title"] = q.Title
	q.fieldMap["icon_url"] = q.IconURL
	q.fieldMap["icon_text"] = q.IconText
	q.fieldMap["target_url"] = q.TargetURL
	q.fieldMap["description"] = q.Description
	q.fieldMap["visible_role_codes"] = q.VisibleRoleCodes
	q.fieldMap["sort_order"] = q.SortOrder
	q.fieldMap["status"] = q.Status
	q.fieldMap["created_by"] = q.CreatedBy
	q.fieldMap["updated_by"] = q.UpdatedBy
	q.fieldMap["created_at"] = q.CreatedAt
	q.fieldMap["updated_at"] = q.UpdatedAt
}

func (q quickEntry) clone(db *gorm.DB) quickEntry {
	q.quickEntryDo.ReplaceConnPool(db.Statement.ConnPool)
	return q
}

func (q quickEntry) replaceDB(db *gorm.DB) quickEntry {
	q.quickEntryDo.ReplaceDB(db)
	return q
}

type quickEntryDo struct{ gen.DO }

type IQuickEntryDo interface {
	gen.SubQuery
	Debug() IQuickEntryDo
	WithContext(ctx context.Context) IQuickEntryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IQuickEntryDo
	WriteDB() IQuickEntryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IQuickEntryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IQuickEntryDo
	Not(conds ...gen.Condition) IQuickEntryDo
	Or(conds ...gen.Condition) IQuickEntryDo
	Select(conds ...field.Expr) IQuickEntryDo
	Where(conds ...gen.Condition) IQuickEntryDo
	Order(conds ...field.Expr) IQuickEntryDo
	Distinct(cols ...field.Expr) IQuickEntryDo
	Omit(cols ...field.Expr) IQuickEntryDo
	Join(table schema.Tabler, on ...field.Expr) IQuickEntryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IQuickEntryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IQuickEntryDo
	Group(cols ...field.Expr) IQuickEntryDo
	Having(conds ...gen.Condition) IQuickEntryDo
	Limit(limit int) IQuickEntryDo
	Offset(offset int) IQuickEntryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IQuickEntryDo
	Unscoped() IQuickEntryDo
	Create(values ...*model.QuickEntry) error
	CreateInBatches(values []*model.QuickEntry, batchSize int) error
	Save(values ...*model.QuickEntry) error
	First() (*model.QuickEntry, error)
	Take() (*model.QuickEntry, error)
	Last() (*model.QuickEntry, error)
	Find() ([]*model.QuickEntry, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.QuickEntry, err error)
	FindInBatches(result *[]*model.QuickEntry, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.QuickEntry) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IQuickEntryDo
	Assign(attrs ...field.AssignExpr) IQuickEntryDo
	Joins(fields ...field.RelationField) IQuickEntryDo
	Preload(fields ...field.RelationField) IQuickEntryDo
	FirstOrInit() (*model.QuickEntry, error)
	FirstOrCreate() (*model.QuickEntry, error)
	FindByPage(offset int, limit int) (result []*model.QuickEntry, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IQuickEntryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (q quickEntryDo) Debug() IQuickEntryDo {
	return q.withDO(q.DO.Debug())
}

func (q quickEntryDo) WithContext(ctx context.Context) IQuickEntryDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q quickEntryDo) ReadDB() IQuickEntryDo {
	return q.Clauses(dbresolver.Read)
}

func (q quickEntryDo) WriteDB() IQuickEntryDo {
	return q.Clauses(dbresolver.Write)
}

func (q quickEntryDo) Session(config *gorm.Session) IQuickEntryDo {
	return q.withDO(q.DO.Session(config))
}

func (q quickEntryDo) Clauses(conds ...clause.Expression) IQuickEntryDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q quickEntryDo) Returning(value interface{}, columns ...string) IQuickEntryDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q quickEntryDo) Not(conds ...gen.Condition) IQuickEntryDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q quickEntryDo) Or(conds ...gen.Condition) IQuickEntryDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q quickEntryDo) Select(conds ...field.Expr) IQuickEntryDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q quickEntryDo) Where(conds ...gen.Condition) IQuickEntryDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q quickEntryDo) Order(conds ...field.Expr) IQuickEntryDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q quickEntryDo) Distinct(cols ...field.Expr) IQuickEntryDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q quickEntryDo) Omit(cols ...field.Expr) IQuickEntryDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q quickEntryDo) Join(table schema.Tabler, on ...field.Expr) IQuickEntryDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q quickEntryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IQuickEntryDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q quickEntryDo) RightJoin(table schema.Tabler, on ...field.Expr) IQuickEntryDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q quickEntryDo) Group(cols ...field.Expr) IQuickEntryDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q quickEntryDo) Having(conds ...gen.Condition) IQuickEntryDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q quickEntryDo) Limit(limit int) IQuickEntryDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q quickEntryDo) Offset(offset int) IQuickEntryDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q quickEntryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IQuickEntryDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q quickEntryDo) Unscoped() IQuickEntryDo {
	return q.withDO(q.DO.Unscoped())
}

func (q quickEntryDo) Create(values ...*model.QuickEntry) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q quickEntryDo) CreateInBatches(values []*model.QuickEntry, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q quickEntryDo) Save(values ...*model.QuickEntry) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q quickEntryDo) First() (*model.QuickEntry, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuickEntry), nil
	}
}

func (q quickEntryDo) Take() (*model.QuickEntry, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuickEntry), nil
	}
}

func (q quickEntryDo) Last() (*model.QuickEntry, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuickEntry), nil
	}
}

func (q quickEntryDo) Find() ([]*model.QuickEntry, error) {
	result, err := q.DO.Find()
	return result.([]*model.QuickEntry), err
}

func (q quickEntryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.QuickEntry, err error) {
	buf := make([]*model.QuickEntry, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q quickEntryDo) FindInBatches(result *[]*model.QuickEntry, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q quickEntryDo) Attrs(attrs ...field.AssignExpr) IQuickEntryDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q quickEntryDo) Assign(attrs ...field.AssignExpr) IQuickEntryDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q quickEntryDo) Joins(fields ...field.RelationField) IQuickEntryDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q quickEntryDo) Preload(fields ...field.RelationField) IQuickEntryDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q quickEntryDo) FirstOrInit() (*model.QuickEntry, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuickEntry), nil
	}
}

func (q quickEntryDo) FirstOrCreate() (*model.QuickEntry, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuickEntry), nil
	}
}

func (q quickEntryDo) FindByPage(offset int, limit int) (result []*model.QuickEntry, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q quickEntryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q quickEntryDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q quickEntryDo) Delete(models ...*model.QuickEntry) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *quickEntryDo) withDO(do gen.Dao) *quickEntryDo {
	q.DO = *do.(*gen.DO)
	return q
}
