// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yang/wormhole_backend/internal/dal/model"
)

func newRecommendationItem(db *gorm.DB, opts ...gen.DOOption) recommendationItem {
	_recommendationItem := recommendationItem{}

	_recommendationItem.recommendationItemDo.UseDB(db, opts...)
	_recommendationItem.recommendationItemDo.UseModel(&model.RecommendationItem{})

	tableName := _recommendationItem.recommendationItemDo.TableName()
	_recommendationItem.ALL = field.NewAsterisk(tableName)
	_recommendationItem.ID = field.NewInt64(tableName, "id")
	_recommendationItem.ResourceID = field.NewInt64(tableName, "resource_id")
	_recommendationItem.Title = field.NewString(tableName, "title")
	_recommendationItem.Subtitle = field.NewString(tableName, "subtitle")
	_recommendationItem.SourceName = field.NewString(tableName, "source_name")
	_recommendationItem.SourceURL = field.NewString(tableName, "source_url")
	_recommendationItem.IconURL = field.NewString(tableName, "icon_url")
	_recommendationItem.IconText = field.NewString(tableName, "icon_text")
	_recommendationItem.TargetURL = field.NewString(tableName, "target_url")
	_recommendationItem.PublishedAt = field.NewTime(tableName, "published_at")
	_recommendationItem.VisibleRoleCodes = field.NewString(tableName, "visible_role_codes")
	_recommendationItem.SortOrder = field.NewInt32(tableName, "sort_order")
	_recommendationItem.Status = field.NewInt16(tableName, "status")
	_recommendationItem.CreatedBy = field.NewInt64(tableName, "created_by")
	_recommendationItem.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_recommendationItem.CreatedAt = field.NewTime(tableName, "created_at")
	_recommendationItem.UpdatedAt = field.NewTime(tableName, "updated_at")

	_recommendationItem.fillFieldMap()

	return _recommendationItem
}

type recommendationItem struct {
	recommendationItemDo

	ALL              field.Asterisk
	ID               field.Int64
	ResourceID       field.Int64
	Title            field.String
	Subtitle         field.String
	SourceName       field.String
	SourceURL        field.String
	IconURL          field.String
	IconText         field.String
	TargetURL        field.String
	PublishedAt      field.Time
	VisibleRoleCodes field.String
	SortOrder        field.Int32
	Status           field.Int16
	CreatedBy        field.Int64
	UpdatedBy        field.Int64
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (r recommendationItem) Table(newTableName string) *recommendationItem {
	r.recommendationItemDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r recommendationItem) As(alias string) *recommendationItem {
	r.recommendationItemDo.DO = *(r.recommendationItemDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *recommendationItem) updateTableName(table string) *recommendationItem {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.ResourceID = field.NewInt64(table, "resource_id")
	r.Title = field.NewString(table, "title")
	r.Subtitle = field.NewString(table, "subtitle")
	r.SourceName = field.NewString(table, "source_name")
	r.SourceURL = field.NewString(table, "source_url")
	r.IconURL = field.NewString(table, "icon_url")
	r.IconText = field.NewString(table, "icon_text")
	r.TargetURL = field.NewString(table, "target_url")
	r.PublishedAt = field.NewTime(table, "published_at")
	r.VisibleRoleCodes = field.NewString(table, "visible_role_codes")
	r.SortOrder = field.NewInt32(table, "sort_order")
	r.Status = field.NewInt16(table, "status")
	r.CreatedBy = field.NewInt64(table, "created_by")
	r.UpdatedBy = field.NewInt64(table, "updated_by")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *recommendationItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *recommendationItem) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 17)
	r.fieldMap["id"] = r.ID
	r.fieldMap["resource_id"] = r.ResourceID
	r.fieldMap["title"] = r.Title
	r.fieldMap["subtitle"] = r.Subtitle
	r.fieldMap["source_name"] = r.SourceName
	r.fieldMap["source_url"] = r.SourceURL
	r.fieldMap["icon_url"] = r.IconURL
	r.fieldMap["icon_text"] = r.IconText
	r.fieldMap["target_url"] = r.TargetURL
	r.fieldMap["published_at"] = r.PublishedAt
	r.fieldMap["visible_role_codes"] = r.VisibleRoleCodes
	r.fieldMap["sort_order"] = r.SortOrder
	r.fieldMap["status"] = r.Status
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["updated_by"] = r.UpdatedBy
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r recommendationItem) clone(db *gorm.DB) recommendationItem {
	r.recommendationItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r recommendationItem) replaceDB(db *gorm.DB) recommendationItem {
	r.recommendationItemDo.ReplaceDB(db)
	return r
}

type recommendationItemDo struct{ gen.DO }

type IRecommendationItemDo interface {
	gen.SubQuery
	Debug() IRecommendationItemDo
	WithContext(ctx context.Context) IRecommendationItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRecommendationItemDo
	WriteDB() IRecommendationItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRecommendationItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRecommendationItemDo
	Not(conds ...gen.Condition) IRecommendationItemDo
	Or(conds ...gen.Condition) IRecommendationItemDo
	Select(conds ...field.Expr) IRecommendationItemDo
	Where(conds ...gen.Condition) IRecommendationItemDo
	Order(conds ...field.Expr) IRecommendationItemDo
	Distinct(cols ...field.Expr) IRecommendationItemDo
	Omit(cols ...field.Expr) IRecommendationItemDo
	Join(table schema.Tabler, on ...field.Expr) IRecommendationItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRecommendationItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRecommendationItemDo
	Group(cols ...field.Expr) IRecommendationItemDo
	Having(conds ...gen.Condition) IRecommendationItemDo
	Limit(limit int) IRecommendationItemDo
	Offset(offset int) IRecommendationItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRecommendationItemDo
	Unscoped() IRecommendationItemDo
	Create(values ...*model.RecommendationItem) error
	CreateInBatches(values []*model.RecommendationItem, batchSize int) error
	Save(values ...*model.RecommendationItem) error
	First() (*model.RecommendationItem, error)
	Take() (*model.RecommendationItem, error)
	Last() (*model.RecommendationItem, error)
	Find() ([]*model.RecommendationItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RecommendationItem, err error)
	FindInBatches(result *[]*model.RecommendationItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RecommendationItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRecommendationItemDo
	Assign(attrs ...field.AssignExpr) IRecommendationItemDo
	Joins(fields ...field.RelationField) IRecommendationItemDo
	Preload(fields ...field.RelationField) IRecommendationItemDo
	FirstOrInit() (*model.RecommendationItem, error)
	FirstOrCreate() (*model.RecommendationItem, error)
	FindByPage(offset int, limit int) (result []*model.RecommendationItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRecommendationItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r recommendationItemDo) Debug() IRecommendationItemDo {
	return r.withDO(r.DO.Debug())
}

func (r recommendationItemDo) WithContext(ctx context.Context) IRecommendationItemDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r recommendationItemDo) ReadDB() IRecommendationItemDo {
	return r.Clauses(dbresolver.Read)
}

func (r recommendationItemDo) WriteDB() IRecommendationItemDo {
	return r.Clauses(dbresolver.Write)
}

func (r recommendationItemDo) Session(config *gorm.Session) IRecommendationItemDo {
	return r.withDO(r.DO.Session(config))
}

func (r recommendationItemDo) Clauses(conds ...clause.Expression) IRecommendationItemDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r recommendationItemDo) Returning(value interface{}, columns ...string) IRecommendationItemDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r recommendationItemDo) Not(conds ...gen.Condition) IRecommendationItemDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r recommendationItemDo) Or(conds ...gen.Condition) IRecommendationItemDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r recommendationItemDo) Select(conds ...field.Expr) IRecommendationItemDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r recommendationItemDo) Where(conds ...gen.Condition) IRecommendationItemDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r recommendationItemDo) Order(conds ...field.Expr) IRecommendationItemDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r recommendationItemDo) Distinct(cols ...field.Expr) IRecommendationItemDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r recommendationItemDo) Omit(cols ...field.Expr) IRecommendationItemDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r recommendationItemDo) Join(table schema.Tabler, on ...field.Expr) IRecommendationItemDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r recommendationItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRecommendationItemDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r recommendationItemDo) RightJoin(table schema.Tabler, on ...field.Expr) IRecommendationItemDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r recommendationItemDo) Group(cols ...field.Expr) IRecommendationItemDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r recommendationItemDo) Having(conds ...gen.Condition) IRecommendationItemDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r recommendationItemDo) Limit(limit int) IRecommendationItemDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r recommendationItemDo) Offset(offset int) IRecommendationItemDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r recommendationItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRecommendationItemDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r recommendationItemDo) Unscoped() IRecommendationItemDo {
	return r.withDO(r.DO.Unscoped())
}

func (r recommendationItemDo) Create(values ...*model.RecommendationItem) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r recommendationItemDo) CreateInBatches(values []*model.RecommendationItem, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r recommendationItemDo) Save(values ...*model.RecommendationItem) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r recommendationItemDo) First() (*model.RecommendationItem, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RecommendationItem), nil
	}
}

func (r recommendationItemDo) Take() (*model.RecommendationItem, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RecommendationItem), nil
	}
}

func (r recommendationItemDo) Last() (*model.RecommendationItem, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RecommendationItem), nil
	}
}

func (r recommendationItemDo) Find() ([]*model.RecommendationItem, error) {
	result, err := r.DO.Find()
	return result.([]*model.RecommendationItem), err
}

func (r recommendationItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RecommendationItem, err error) {
	buf := make([]*model.RecommendationItem, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r recommendationItemDo) FindInBatches(result *[]*model.RecommendationItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r recommendationItemDo) Attrs(attrs ...field.AssignExpr) IRecommendationItemDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r recommendationItemDo) Assign(attrs ...field.AssignExpr) IRecommendationItemDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r recommendationItemDo) Joins(fields ...field.RelationField) IRecommendationItemDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r recommendationItemDo) Preload(fields ...field.RelationField) IRecommendationItemDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r recommendationItemDo) FirstOrInit() (*model.RecommendationItem, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RecommendationItem), nil
	}
}

func (r recommendationItemDo) FirstOrCreate() (*model.RecommendationItem, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RecommendationItem), nil
	}
}

func (r recommendationItemDo) FindByPage(offset int, limit int) (result []*model.RecommendationItem, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r recommendationItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r recommendationItemDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r recommendationItemDo) Delete(models ...*model.RecommendationItem) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *recommendationItemDo) withDO(do gen.Dao) *recommendationItemDo {
	r.DO = *do.(*gen.DO)
	return r
}
