// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yang/wormhole_backend/internal/dal/model"
)

func newResource(db *gorm.DB, opts ...gen.DOOption) resource {
	_resource := resource{}

	_resource.resourceDo.UseDB(db, opts...)
	_resource.resourceDo.UseModel(&model.Resource{})

	tableName := _resource.resourceDo.TableName()
	_resource.ALL = field.NewAsterisk(tableName)
	_resource.ID = field.NewInt64(tableName, "id")
	_resource.CategoryID = field.NewInt32(tableName, "category_id")
	_resource.Slug = field.NewString(tableName, "slug")
	_resource.Name = field.NewString(tableName, "name")
	_resource.IconURL = field.NewString(tableName, "icon_url")
	_resource.IconText = field.NewString(tableName, "icon_text")
	_resource.WebsiteURL = field.NewString(tableName, "website_url")
	_resource.Summary = field.NewString(tableName, "summary")
	_resource.Description = field.NewString(tableName, "description")
	_resource.ResourceType = field.NewString(tableName, "resource_type")
	_resource.Provider = field.NewString(tableName, "provider")
	_resource.ModelCount = field.NewInt32(tableName, "model_count")
	_resource.FollowerCount = field.NewInt32(tableName, "follower_count")
	_resource.Badge = field.NewString(tableName, "badge")
	_resource.Tags = field.NewString(tableName, "tags")
	_resource.Metadata = field.NewString(tableName, "metadata")
	_resource.IsFeatured = field.NewBool(tableName, "is_featured")
	_resource.SortOrder = field.NewInt32(tableName, "sort_order")
	_resource.Status = field.NewInt16(tableName, "status")
	_resource.CreatedBy = field.NewInt64(tableName, "created_by")
	_resource.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_resource.CreatedAt = field.NewTime(tableName, "created_at")
	_resource.UpdatedAt = field.NewTime(tableName, "updated_at")

	_resource.fillFieldMap()

	return _resource
}

type resource struct {
	resourceDo

	ALL           field.Asterisk
	ID            field.Int64
	CategoryID    field.Int32
	Slug          field.String
	Name          field.String
	IconURL       field.String
	IconText      field.String
	WebsiteURL    field.String
	Summary       field.String
	Description   field.String
	ResourceType  field.String
	Provider      field.String
	ModelCount    field.Int32
	FollowerCount field.Int32
	Badge         field.String
	Tags          field.String
	Metadata      field.String
	IsFeatured    field.Bool
	SortOrder     field.Int32
	Status        field.Int16
	CreatedBy     field.Int64
	UpdatedBy     field.Int64
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (r resource) Table(newTableName string) *resource {
	r.resourceDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resource) As(alias string) *resource {
	r.resourceDo.DO = *(r.resourceDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resource) updateTableName(table string) *resource {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.CategoryID = field.NewInt32(table, "category_id")
	r.Slug = field.NewString(table, "slug")
	r.Name = field.NewString(table, "name")
	r.IconURL = field.NewString(table, "icon_url")
	r.IconText = field.NewString(table, "icon_text")
	r.WebsiteURL = field.NewString(table, "website_url")
	r.Summary = field.NewString(table, "summary")
	r.Description = field.NewString(table, "description")
	r.ResourceType = field.NewString(table, "resource_type")
	r.Provider = field.NewString(table, "provider")
	r.ModelCount = field.NewInt32(table, "model_count")
	r.FollowerCount = field.NewInt32(table, "follower_count")
	r.Badge = field.NewString(table, "badge")
	r.Tags = field.NewString(table, "tags")
	r.Metadata = field.NewString(table, "metadata")
	r.IsFeatured = field.NewBool(table, "is_featured")
	r.SortOrder = field.NewInt32(table, "sort_order")
	r.Status = field.NewInt16(table, "status")
	r.CreatedBy = field.NewInt64(table, "created_by")
	r.UpdatedBy = field.NewInt64(table, "updated_by")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *resource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resource) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 23)
	r.fieldMap["id"] = r.ID
	r.fieldMap["category_id"] = r.CategoryID
	r.fieldMap["slug"] = r.Slug
	r.fieldMap["name"] = r.Name
	r.fieldMap["icon_url"] = r.IconURL
	r.fieldMap["icon_text"] = r.IconText
	r.fieldMap["website_url"] = r.WebsiteURL
	r.fieldMap["summary"] = r.Summary
	r.fieldMap["description"] = r.Description
	r.fieldMap["resource_type"] = r.ResourceType
	r.fieldMap["provider"] = r.Provider
	r.fieldMap["model_count"] = r.ModelCount
	r.fieldMap["follower_count"] = r.FollowerCount
	r.fieldMap["badge"] = r.Badge
	r.fieldMap["tags"] = r.Tags
	r.fieldMap["metadata"] = r.Metadata
	r.fieldMap["is_featured"] = r.IsFeatured
	r.fieldMap["sort_order"] = r.SortOrder
	r.fieldMap["status"] = r.Status
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["updated_by"] = r.UpdatedBy
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r resource) clone(db *gorm.DB) resource {
	r.resourceDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resource) replaceDB(db *gorm.DB) resource {
	r.resourceDo.ReplaceDB(db)
	return r
}

type resourceDo struct{ gen.DO }

type IResourceDo interface {
	gen.SubQuery
	Debug() IResourceDo
	WithContext(ctx context.Context) IResourceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IResourceDo
	WriteDB() IResourceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IResourceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IResourceDo
	Not(conds ...gen.Condition) IResourceDo
	Or(conds ...gen.Condition) IResourceDo
	Select(conds ...field.Expr) IResourceDo
	Where(conds ...gen.Condition) IResourceDo
	Order(conds ...field.Expr) IResourceDo
	Distinct(cols ...field.Expr) IResourceDo
	Omit(cols ...field.Expr) IResourceDo
	Join(table schema.Tabler, on ...field.Expr) IResourceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IResourceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IResourceDo
	Group(cols ...field.Expr) IResourceDo
	Having(conds ...gen.Condition) IResourceDo
	Limit(limit int) IResourceDo
	Offset(offset int) IResourceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceDo
	Unscoped() IResourceDo
	Create(values ...*model.Resource) error
	CreateInBatches(values []*model.Resource, batchSize int) error
	Save(values ...*model.Resource) error
	First() (*model.Resource, error)
	Take() (*model.Resource, error)
	Last() (*model.Resource, error)
	Find() ([]*model.Resource, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Resource, err error)
	FindInBatches(result *[]*model.Resource, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Resource) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IResourceDo
	Assign(attrs ...field.AssignExpr) IResourceDo
	Joins(fields ...field.RelationField) IResourceDo
	Preload(fields ...field.RelationField) IResourceDo
	FirstOrInit() (*model.Resource, error)
	FirstOrCreate() (*model.Resource, error)
	FindByPage(offset int, limit int) (result []*model.Resource, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IResourceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r resourceDo) Debug() IResourceDo {
	return r.withDO(r.DO.Debug())
}

func (r resourceDo) WithContext(ctx context.Context) IResourceDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resourceDo) ReadDB() IResourceDo {
	return r.Clauses(dbresolver.Read)
}

func (r resourceDo) WriteDB() IResourceDo {
	return r.Clauses(dbresolver.Write)
}

func (r resourceDo) Session(config *gorm.Session) IResourceDo {
	return r.withDO(r.DO.Session(config))
}

func (r resourceDo) Clauses(conds ...clause.Expression) IResourceDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resourceDo) Returning(value interface{}, columns ...string) IResourceDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resourceDo) Not(conds ...gen.Condition) IResourceDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resourceDo) Or(conds ...gen.Condition) IResourceDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resourceDo) Select(conds ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resourceDo) Where(conds ...gen.Condition) IResourceDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resourceDo) Order(conds ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resourceDo) Distinct(cols ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resourceDo) Omit(cols ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resourceDo) Join(table schema.Tabler, on ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IResourceDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resourceDo) RightJoin(table schema.Tabler, on ...field.Expr) IResourceDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resourceDo) Group(cols ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resourceDo) Having(conds ...gen.Condition) IResourceDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resourceDo) Limit(limit int) IResourceDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resourceDo) Offset(offset int) IResourceDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resourceDo) Unscoped() IResourceDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resourceDo) Create(values ...*model.Resource) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resourceDo) CreateInBatches(values []*model.Resource, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resourceDo) Save(values ...*model.Resource) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resourceDo) First() (*model.Resource, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resource), nil
	}
}

func (r resourceDo) Take() (*model.Resource, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resource), nil
	}
}

func (r resourceDo) Last() (*model.Resource, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resource), nil
	}
}

func (r resourceDo) Find() ([]*model.Resource, error) {
	result, err := r.DO.Find()
	return result.([]*model.Resource), err
}

func (r resourceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Resource, err error) {
	buf := make([]*model.Resource, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resourceDo) FindInBatches(result *[]*model.Resource, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resourceDo) Attrs(attrs ...field.AssignExpr) IResourceDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resourceDo) Assign(attrs ...field.AssignExpr) IResourceDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resourceDo) Joins(fields ...field.RelationField) IResourceDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resourceDo) Preload(fields ...field.RelationField) IResourceDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resourceDo) FirstOrInit() (*model.Resource, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resource), nil
	}
}

func (r resourceDo) FirstOrCreate() (*model.Resource, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resource), nil
	}
}

func (r resourceDo) FindByPage(offset int, limit int) (result []*model.Resource, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resourceDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resourceDo) Delete(models ...*model.Resource) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resourceDo) withDO(do gen.Dao) *resourceDo {
	r.DO = *do.(*gen.DO)
	return r
}
