// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yang/wormhole_backend/internal/dal/model"
)

func newResourceCategory(db *gorm.DB, opts ...gen.DOOption) resourceCategory {
	_resourceCategory := resourceCategory{}

	_resourceCategory.resourceCategoryDo.UseDB(db, opts...)
	_resourceCategory.resourceCategoryDo.UseModel(&model.ResourceCategory{})

	tableName := _resourceCategory.resourceCategoryDo.TableName()
	_resourceCategory.ALL = field.NewAsterisk(tableName)
	_resourceCategory.ID = field.NewInt32(tableName, "id")
	_resourceCategory.Code = field.NewString(tableName, "code")
	_resourceCategory.Name = field.NewString(tableName, "name")
	_resourceCategory.Description = field.NewString(tableName, "description")
	_resourceCategory.SortOrder = field.NewInt32(tableName, "sort_order")
	_resourceCategory.Status = field.NewInt16(tableName, "status")
	_resourceCategory.CreatedBy = field.NewInt64(tableName, "created_by")
	_resourceCategory.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_resourceCategory.CreatedAt = field.NewTime(tableName, "created_at")
	_resourceCategory.UpdatedAt = field.NewTime(tableName, "updated_at")

	_resourceCategory.fillFieldMap()

	return _resourceCategory
}

type resourceCategory struct {
	resourceCategoryDo

	ALL         field.Asterisk
	ID          field.Int32
	Code        field.String
	Name        field.String
	Description field.String
	SortOrder   field.Int32
	Status      field.Int16
	CreatedBy   field.Int64
	UpdatedBy   field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (r resourceCategory) Table(newTableName string) *resourceCategory {
	r.resourceCategoryDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resourceCategory) As(alias string) *resourceCategory {
	r.resourceCategoryDo.DO = *(r.resourceCategoryDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resourceCategory) updateTableName(table string) *resourceCategory {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.Code = field.NewString(table, "code")
	r.Name = field.NewString(table, "name")
	r.Description = field.NewString(table, "description")
	r.SortOrder = field.NewInt32(table, "sort_order")
	r.Status = field.NewInt16(table, "status")
	r.CreatedBy = field.NewInt64(table, "created_by")
	r.UpdatedBy = field.NewInt64(table, "updated_by")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *resourceCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resourceCategory) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 10)
	r.fieldMap["id"] = r.ID
	r.fieldMap["code"] = r.Code
	r.fieldMap["name"] = r.Name
	r.fieldMap["description"] = r.Description
	r.fieldMap["sort_order"] = r.SortOrder
	r.fieldMap["status"] = r.Status
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["updated_by"] = r.UpdatedBy
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r resourceCategory) clone(db *gorm.DB) resourceCategory {
	r.resourceCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resourceCategory) replaceDB(db *gorm.DB) resourceCategory {
	r.resourceCategoryDo.ReplaceDB(db)
	return r
}

type resourceCategoryDo struct{ gen.DO }

type IResourceCategoryDo interface {
	gen.SubQuery
	Debug() IResourceCategoryDo
	WithContext(ctx context.Context) IResourceCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IResourceCategoryDo
	WriteDB() IResourceCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IResourceCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IResourceCategoryDo
	Not(conds ...gen.Condition) IResourceCategoryDo
	Or(conds ...gen.Condition) IResourceCategoryDo
	Select(conds ...field.Expr) IResourceCategoryDo
	Where(conds ...gen.Condition) IResourceCategoryDo
	Order(conds ...field.Expr) IResourceCategoryDo
	Distinct(cols ...field.Expr) IResourceCategoryDo
	Omit(cols ...field.Expr) IResourceCategoryDo
	Join(table schema.Tabler, on ...field.Expr) IResourceCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IResourceCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IResourceCategoryDo
	Group(cols ...field.Expr) IResourceCategoryDo
	Having(conds ...gen.Condition) IResourceCategoryDo
	Limit(limit int) IResourceCategoryDo
	Offset(offset int) IResourceCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceCategoryDo
	Unscoped() IResourceCategoryDo
	Create(values ...*model.ResourceCategory) error
	CreateInBatches(values []*model.ResourceCategory, batchSize int) error
	Save(values ...*model.ResourceCategory) error
	First() (*model.ResourceCategory, error)
	Take() (*model.ResourceCategory, error)
	Last() (*model.ResourceCategory, error)
	Find() ([]*model.ResourceCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResourceCategory, err error)
	FindInBatches(result *[]*model.ResourceCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ResourceCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IResourceCategoryDo
	Assign(attrs ...field.AssignExpr) IResourceCategoryDo
	Joins(fields ...field.RelationField) IResourceCategoryDo
	Preload(fields ...field.RelationField) IResourceCategoryDo
	FirstOrInit() (*model.ResourceCategory, error)
	FirstOrCreate() (*model.ResourceCategory, error)
	FindByPage(offset int, limit int) (result []*model.ResourceCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IResourceCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r resourceCategoryDo) Debug() IResourceCategoryDo {
	return r.withDO(r.DO.Debug())
}

func (r resourceCategoryDo) WithContext(ctx context.Context) IResourceCategoryDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resourceCategoryDo) ReadDB() IResourceCategoryDo {
	return r.Clauses(dbresolver.Read)
}

func (r resourceCategoryDo) WriteDB() IResourceCategoryDo {
	return r.Clauses(dbresolver.Write)
}

func (r resourceCategoryDo) Session(config *gorm.Session) IResourceCategoryDo {
	return r.withDO(r.DO.Session(config))
}

func (r resourceCategoryDo) Clauses(conds ...clause.Expression) IResourceCategoryDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resourceCategoryDo) Returning(value interface{}, columns ...string) IResourceCategoryDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resourceCategoryDo) Not(conds ...gen.Condition) IResourceCategoryDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resourceCategoryDo) Or(conds ...gen.Condition) IResourceCategoryDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resourceCategoryDo) Select(conds ...field.Expr) IResourceCategoryDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resourceCategoryDo) Where(conds ...gen.Condition) IResourceCategoryDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resourceCategoryDo) Order(conds ...field.Expr) IResourceCategoryDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resourceCategoryDo) Distinct(cols ...field.Expr) IResourceCategoryDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resourceCategoryDo) Omit(cols ...field.Expr) IResourceCategoryDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resourceCategoryDo) Join(table schema.Tabler, on ...field.Expr) IResourceCategoryDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resourceCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IResourceCategoryDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resourceCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IResourceCategoryDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resourceCategoryDo) Group(cols ...field.Expr) IResourceCategoryDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resourceCategoryDo) Having(conds ...gen.Condition) IResourceCategoryDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resourceCategoryDo) Limit(limit int) IResourceCategoryDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resourceCategoryDo) Offset(offset int) IResourceCategoryDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resourceCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceCategoryDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resourceCategoryDo) Unscoped() IResourceCategoryDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resourceCategoryDo) Create(values ...*model.ResourceCategory) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resourceCategoryDo) CreateInBatches(values []*model.ResourceCategory, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resourceCategoryDo) Save(values ...*model.ResourceCategory) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resourceCategoryDo) First() (*model.ResourceCategory, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceCategory), nil
	}
}

func (r resourceCategoryDo) Take() (*model.ResourceCategory, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceCategory), nil
	}
}

func (r resourceCategoryDo) Last() (*model.ResourceCategory, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceCategory), nil
	}
}

func (r resourceCategoryDo) Find() ([]*model.ResourceCategory, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResourceCategory), err
}

func (r resourceCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResourceCategory, err error) {
	buf := make([]*model.ResourceCategory, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resourceCategoryDo) FindInBatches(result *[]*model.ResourceCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resourceCategoryDo) Attrs(attrs ...field.AssignExpr) IResourceCategoryDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resourceCategoryDo) Assign(attrs ...field.AssignExpr) IResourceCategoryDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resourceCategoryDo) Joins(fields ...field.RelationField) IResourceCategoryDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resourceCategoryDo) Preload(fields ...field.RelationField) IResourceCategoryDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resourceCategoryDo) FirstOrInit() (*model.ResourceCategory, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceCategory), nil
	}
}

func (r resourceCategoryDo) FirstOrCreate() (*model.ResourceCategory, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceCategory), nil
	}
}

func (r resourceCategoryDo) FindByPage(offset int, limit int) (result []*model.ResourceCategory, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resourceCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resourceCategoryDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resourceCategoryDo) Delete(models ...*model.ResourceCategory) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resourceCategoryDo) withDO(do gen.Dao) *resourceCategoryDo {
	r.DO = *do.(*gen.DO)
	return r
}
