// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yang/wormhole_backend/internal/dal/model"
)

func newUserCommonTool(db *gorm.DB, opts ...gen.DOOption) userCommonTool {
	_userCommonTool := userCommonTool{}

	_userCommonTool.userCommonToolDo.UseDB(db, opts...)
	_userCommonTool.userCommonToolDo.UseModel(&model.UserCommonTool{})

	tableName := _userCommonTool.userCommonToolDo.TableName()
	_userCommonTool.ALL = field.NewAsterisk(tableName)
	_userCommonTool.UserID = field.NewInt64(tableName, "user_id")
	_userCommonTool.ResourceID = field.NewInt64(tableName, "resource_id")
	_userCommonTool.SortOrder = field.NewInt32(tableName, "sort_order")
	_userCommonTool.CreatedAt = field.NewTime(tableName, "created_at")

	_userCommonTool.fillFieldMap()

	return _userCommonTool
}

type userCommonTool struct {
	userCommonToolDo

	ALL        field.Asterisk
	UserID     field.Int64
	ResourceID field.Int64
	SortOrder  field.Int32
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (u userCommonTool) Table(newTableName string) *userCommonTool {
	u.userCommonToolDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userCommonTool) As(alias string) *userCommonTool {
	u.userCommonToolDo.DO = *(u.userCommonToolDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userCommonTool) updateTableName(table string) *userCommonTool {
	u.ALL = field.NewAsterisk(table)
	u.UserID = field.NewInt64(table, "user_id")
	u.ResourceID = field.NewInt64(table, "resource_id")
	u.SortOrder = field.NewInt32(table, "sort_order")
	u.CreatedAt = field.NewTime(table, "created_at")

	u.fillFieldMap()

	return u
}

func (u *userCommonTool) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userCommonTool) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 4)
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["resource_id"] = u.ResourceID
	u.fieldMap["sort_order"] = u.SortOrder
	u.fieldMap["created_at"] = u.CreatedAt
}

func (u userCommonTool) clone(db *gorm.DB) userCommonTool {
	u.userCommonToolDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userCommonTool) replaceDB(db *gorm.DB) userCommonTool {
	u.userCommonToolDo.ReplaceDB(db)
	return u
}

type userCommonToolDo struct{ gen.DO }

type IUserCommonToolDo interface {
	gen.SubQuery
	Debug() IUserCommonToolDo
	WithContext(ctx context.Context) IUserCommonToolDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserCommonToolDo
	WriteDB() IUserCommonToolDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserCommonToolDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserCommonToolDo
	Not(conds ...gen.Condition) IUserCommonToolDo
	Or(conds ...gen.Condition) IUserCommonToolDo
	Select(conds ...field.Expr) IUserCommonToolDo
	Where(conds ...gen.Condition) IUserCommonToolDo
	Order(conds ...field.Expr) IUserCommonToolDo
	Distinct(cols ...field.Expr) IUserCommonToolDo
	Omit(cols ...field.Expr) IUserCommonToolDo
	Join(table schema.Tabler, on ...field.Expr) IUserCommonToolDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserCommonToolDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserCommonToolDo
	Group(cols ...field.Expr) IUserCommonToolDo
	Having(conds ...gen.Condition) IUserCommonToolDo
	Limit(limit int) IUserCommonToolDo
	Offset(offset int) IUserCommonToolDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserCommonToolDo
	Unscoped() IUserCommonToolDo
	Create(values ...*model.UserCommonTool) error
	CreateInBatches(values []*model.UserCommonTool, batchSize int) error
	Save(values ...*model.UserCommonTool) error
	First() (*model.UserCommonTool, error)
	Take() (*model.UserCommonTool, error)
	Last() (*model.UserCommonTool, error)
	Find() ([]*model.UserCommonTool, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserCommonTool, err error)
	FindInBatches(result *[]*model.UserCommonTool, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserCommonTool) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserCommonToolDo
	Assign(attrs ...field.AssignExpr) IUserCommonToolDo
	Joins(fields ...field.RelationField) IUserCommonToolDo
	Preload(fields ...field.RelationField) IUserCommonToolDo
	FirstOrInit() (*model.UserCommonTool, error)
	FirstOrCreate() (*model.UserCommonTool, error)
	FindByPage(offset int, limit int) (result []*model.UserCommonTool, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserCommonToolDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userCommonToolDo) Debug() IUserCommonToolDo {
	return u.withDO(u.DO.Debug())
}

func (u userCommonToolDo) WithContext(ctx context.Context) IUserCommonToolDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userCommonToolDo) ReadDB() IUserCommonToolDo {
	return u.Clauses(dbresolver.Read)
}

func (u userCommonToolDo) WriteDB() IUserCommonToolDo {
	return u.Clauses(dbresolver.Write)
}

func (u userCommonToolDo) Session(config *gorm.Session) IUserCommonToolDo {
	return u.withDO(u.DO.Session(config))
}

func (u userCommonToolDo) Clauses(conds ...clause.Expression) IUserCommonToolDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userCommonToolDo) Returning(value interface{}, columns ...string) IUserCommonToolDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userCommonToolDo) Not(conds ...gen.Condition) IUserCommonToolDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userCommonToolDo) Or(conds ...gen.Condition) IUserCommonToolDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userCommonToolDo) Select(conds ...field.Expr) IUserCommonToolDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userCommonToolDo) Where(conds ...gen.Condition) IUserCommonToolDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userCommonToolDo) Order(conds ...field.Expr) IUserCommonToolDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userCommonToolDo) Distinct(cols ...field.Expr) IUserCommonToolDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userCommonToolDo) Omit(cols ...field.Expr) IUserCommonToolDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userCommonToolDo) Join(table schema.Tabler, on ...field.Expr) IUserCommonToolDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userCommonToolDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserCommonToolDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userCommonToolDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserCommonToolDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userCommonToolDo) Group(cols ...field.Expr) IUserCommonToolDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userCommonToolDo) Having(conds ...gen.Condition) IUserCommonToolDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userCommonToolDo) Limit(limit int) IUserCommonToolDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userCommonToolDo) Offset(offset int) IUserCommonToolDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userCommonToolDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserCommonToolDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userCommonToolDo) Unscoped() IUserCommonToolDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userCommonToolDo) Create(values ...*model.UserCommonTool) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userCommonToolDo) CreateInBatches(values []*model.UserCommonTool, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userCommonToolDo) Save(values ...*model.UserCommonTool) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userCommonToolDo) First() (*model.UserCommonTool, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCommonTool), nil
	}
}

func (u userCommonToolDo) Take() (*model.UserCommonTool, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCommonTool), nil
	}
}

func (u userCommonToolDo) Last() (*model.UserCommonTool, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCommonTool), nil
	}
}

func (u userCommonToolDo) Find() ([]*model.UserCommonTool, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserCommonTool), err
}

func (u userCommonToolDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserCommonTool, err error) {
	buf := make([]*model.UserCommonTool, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userCommonToolDo) FindInBatches(result *[]*model.UserCommonTool, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userCommonToolDo) Attrs(attrs ...field.AssignExpr) IUserCommonToolDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userCommonToolDo) Assign(attrs ...field.AssignExpr) IUserCommonToolDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userCommonToolDo) Joins(fields ...field.RelationField) IUserCommonToolDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userCommonToolDo) Preload(fields ...field.RelationField) IUserCommonToolDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userCommonToolDo) FirstOrInit() (*model.UserCommonTool, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCommonTool), nil
	}
}

func (u userCommonToolDo) FirstOrCreate() (*model.UserCommonTool, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCommonTool), nil
	}
}

func (u userCommonToolDo) FindByPage(offset int, limit int) (result []*model.UserCommonTool, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userCommonToolDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userCommonToolDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userCommonToolDo) Delete(models ...*model.UserCommonTool) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userCommonToolDo) withDO(do gen.Dao) *userCommonToolDo {
	u.DO = *do.(*gen.DO)
	return u
}
