// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yang/wormhole_backend/internal/dal/model"
)

func newWorkspaceChannel(db *gorm.DB, opts ...gen.DOOption) workspaceChannel {
	_workspaceChannel := workspaceChannel{}

	_workspaceChannel.workspaceChannelDo.UseDB(db, opts...)
	_workspaceChannel.workspaceChannelDo.UseModel(&model.WorkspaceChannel{})

	tableName := _workspaceChannel.workspaceChannelDo.TableName()
	_workspaceChannel.ALL = field.NewAsterisk(tableName)
	_workspaceChannel.ID = field.NewInt32(tableName, "id")
	_workspaceChannel.Code = field.NewString(tableName, "code")
	_workspaceChannel.Name = field.NewString(tableName, "name")
	_workspaceChannel.Description = field.NewString(tableName, "description")
	_workspaceChannel.IconURL = field.NewString(tableName, "icon_url")
	_workspaceChannel.IconText = field.NewString(tableName, "icon_text")
	_workspaceChannel.TargetURL = field.NewString(tableName, "target_url")
	_workspaceChannel.VisibleRoleCodes = field.NewString(tableName, "visible_role_codes")
	_workspaceChannel.SortOrder = field.NewInt32(tableName, "sort_order")
	_workspaceChannel.Status = field.NewInt16(tableName, "status")
	_workspaceChannel.CreatedBy = field.NewInt64(tableName, "created_by")
	_workspaceChannel.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_workspaceChannel.CreatedAt = field.NewTime(tableName, "created_at")
	_workspaceChannel.UpdatedAt = field.NewTime(tableName, "updated_at")

	_workspaceChannel.fillFieldMap()

	return _workspaceChannel
}

type workspaceChannel struct {
	workspaceChannelDo

	ALL              field.Asterisk
	ID               field.Int32
	Code             field.String
	Name             field.String
	Description      field.String
	IconURL          field.String
	IconText         field.String
	TargetURL        field.String
	VisibleRoleCodes field.String
	SortOrder        field.Int32
	Status           field.Int16
	CreatedBy        field.Int64
	UpdatedBy        field.Int64
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (w workspaceChannel) Table(newTableName string) *workspaceChannel {
	w.workspaceChannelDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w workspaceChannel) As(alias string) *workspaceChannel {
	w.workspaceChannelDo.DO = *(w.workspaceChannelDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *workspaceChannel) updateTableName(table string) *workspaceChannel {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt32(table, "id")
	w.Code = field.NewString(table, "code")
	w.Name = field.NewString(table, "name")
	w.Description = field.NewString(table, "description")
	w.IconURL = field.NewString(table, "icon_url")
	w.IconText = field.NewString(table, "icon_text")
	w.TargetURL = field.NewString(table, "target_url")
	w.VisibleRoleCodes = field.NewString(table, "visible_role_codes")
	w.SortOrder = field.NewInt32(table, "sort_order")
	w.Status = field.NewInt16(table, "status")
	w.CreatedBy = field.NewInt64(table, "created_by")
	w.UpdatedBy = field.NewInt64(table, "updated_by")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *workspaceChannel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *workspaceChannel) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 14)
	w.fieldMap["id"] = w.ID
	w.fieldMap["code"] = w.Code
	w.fieldMap["name"] = w.Name
	w.fieldMap["description"] = w.Description
	w.fieldMap["icon_url"] = w.IconURL
	w.fieldMap["icon_text"] = w.IconText
	w.fieldMap["target_url"] = w.TargetURL
	w.fieldMap["visible_role_codes"] = w.VisibleRoleCodes
	w.fieldMap["sort_order"] = w.SortOrder
	w.fieldMap["status"] = w.Status
	w.fieldMap["created_by"] = w.CreatedBy
	w.fieldMap["updated_by"] = w.UpdatedBy
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w workspaceChannel) clone(db *gorm.DB) workspaceChannel {
	w.workspaceChannelDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w workspaceChannel) replaceDB(db *gorm.DB) workspaceChannel {
	w.workspaceChannelDo.ReplaceDB(db)
	return w
}

type workspaceChannelDo struct{ gen.DO }

type IWorkspaceChannelDo interface {
	gen.SubQuery
	Debug() IWorkspaceChannelDo
	WithContext(ctx context.Context) IWorkspaceChannelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWorkspaceChannelDo
	WriteDB() IWorkspaceChannelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWorkspaceChannelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWorkspaceChannelDo
	Not(conds ...gen.Condition) IWorkspaceChannelDo
	Or(conds ...gen.Condition) IWorkspaceChannelDo
	Select(conds ...field.Expr) IWorkspaceChannelDo
	Where(conds ...gen.Condition) IWorkspaceChannelDo
	Order(conds ...field.Expr) IWorkspaceChannelDo
	Distinct(cols ...field.Expr) IWorkspaceChannelDo
	Omit(cols ...field.Expr) IWorkspaceChannelDo
	Join(table schema.Tabler, on ...field.Expr) IWorkspaceChannelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWorkspaceChannelDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWorkspaceChannelDo
	Group(cols ...field.Expr) IWorkspaceChannelDo
	Having(conds ...gen.Condition) IWorkspaceChannelDo
	Limit(limit int) IWorkspaceChannelDo
	Offset(offset int) IWorkspaceChannelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWorkspaceChannelDo
	Unscoped() IWorkspaceChannelDo
	Create(values ...*model.WorkspaceChannel) error
	CreateInBatches(values []*model.WorkspaceChannel, batchSize int) error
	Save(values ...*model.WorkspaceChannel) error
	First() (*model.WorkspaceChannel, error)
	Take() (*model.WorkspaceChannel, error)
	Last() (*model.WorkspaceChannel, error)
	Find() ([]*model.WorkspaceChannel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WorkspaceChannel, err error)
	FindInBatches(result *[]*model.WorkspaceChannel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WorkspaceChannel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWorkspaceChannelDo
	Assign(attrs ...field.AssignExpr) IWorkspaceChannelDo
	Joins(fields ...field.RelationField) IWorkspaceChannelDo
	Preload(fields ...field.RelationField) IWorkspaceChannelDo
	FirstOrInit() (*model.WorkspaceChannel, error)
	FirstOrCreate() (*model.WorkspaceChannel, error)
	FindByPage(offset int, limit int) (result []*model.WorkspaceChannel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWorkspaceChannelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w workspaceChannelDo) Debug() IWorkspaceChannelDo {
	return w.withDO(w.DO.Debug())
}

func (w workspaceChannelDo) WithContext(ctx context.Context) IWorkspaceChannelDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w workspaceChannelDo) ReadDB() IWorkspaceChannelDo {
	return w.Clauses(dbresolver.Read)
}

func (w workspaceChannelDo) WriteDB() IWorkspaceChannelDo {
	return w.Clauses(dbresolver.Write)
}

func (w workspaceChannelDo) Session(config *gorm.Session) IWorkspaceChannelDo {
	return w.withDO(w.DO.Session(config))
}

func (w workspaceChannelDo) Clauses(conds ...clause.Expression) IWorkspaceChannelDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w workspaceChannelDo) Returning(value interface{}, columns ...string) IWorkspaceChannelDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w workspaceChannelDo) Not(conds ...gen.Condition) IWorkspaceChannelDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w workspaceChannelDo) Or(conds ...gen.Condition) IWorkspaceChannelDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w workspaceChannelDo) Select(conds ...field.Expr) IWorkspaceChannelDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w workspaceChannelDo) Where(conds ...gen.Condition) IWorkspaceChannelDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w workspaceChannelDo) Order(conds ...field.Expr) IWorkspaceChannelDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w workspaceChannelDo) Distinct(cols ...field.Expr) IWorkspaceChannelDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w workspaceChannelDo) Omit(cols ...field.Expr) IWorkspaceChannelDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w workspaceChannelDo) Join(table schema.Tabler, on ...field.Expr) IWorkspaceChannelDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w workspaceChannelDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWorkspaceChannelDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w workspaceChannelDo) RightJoin(table schema.Tabler, on ...field.Expr) IWorkspaceChannelDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w workspaceChannelDo) Group(cols ...field.Expr) IWorkspaceChannelDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w workspaceChannelDo) Having(conds ...gen.Condition) IWorkspaceChannelDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w workspaceChannelDo) Limit(limit int) IWorkspaceChannelDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w workspaceChannelDo) Offset(offset int) IWorkspaceChannelDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w workspaceChannelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWorkspaceChannelDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w workspaceChannelDo) Unscoped() IWorkspaceChannelDo {
	return w.withDO(w.DO.Unscoped())
}

func (w workspaceChannelDo) Create(values ...*model.WorkspaceChannel) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w workspaceChannelDo) CreateInBatches(values []*model.WorkspaceChannel, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w workspaceChannelDo) Save(values ...*model.WorkspaceChannel) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w workspaceChannelDo) First() (*model.WorkspaceChannel, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceChannel), nil
	}
}

func (w workspaceChannelDo) Take() (*model.WorkspaceChannel, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceChannel), nil
	}
}

func (w workspaceChannelDo) Last() (*model.WorkspaceChannel, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceChannel), nil
	}
}

func (w workspaceChannelDo) Find() ([]*model.WorkspaceChannel, error) {
	result, err := w.DO.Find()
	return result.([]*model.WorkspaceChannel), err
}

func (w workspaceChannelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WorkspaceChannel, err error) {
	buf := make([]*model.WorkspaceChannel, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w workspaceChannelDo) FindInBatches(result *[]*model.WorkspaceChannel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w workspaceChannelDo) Attrs(attrs ...field.AssignExpr) IWorkspaceChannelDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w workspaceChannelDo) Assign(attrs ...field.AssignExpr) IWorkspaceChannelDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w workspaceChannelDo) Joins(fields ...field.RelationField) IWorkspaceChannelDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w workspaceChannelDo) Preload(fields ...field.RelationField) IWorkspaceChannelDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w workspaceChannelDo) FirstOrInit() (*model.WorkspaceChannel, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceChannel), nil
	}
}

func (w workspaceChannelDo) FirstOrCreate() (*model.WorkspaceChannel, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceChannel), nil
	}
}

func (w workspaceChannelDo) FindByPage(offset int, limit int) (result []*model.WorkspaceChannel, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w workspaceChannelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w workspaceChannelDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w workspaceChannelDo) Delete(models ...*model.WorkspaceChannel) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *workspaceChannelDo) withDO(do gen.Dao) *workspaceChannelDo {
	w.DO = *do.(*gen.DO)
	return w
}
