// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCarouselSlide = "carousel_slides"

// CarouselSlide mapped from table <carousel_slides>
type CarouselSlide struct {
	ID               int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_carousel_slides_status_sort,priority:1" json:"id"`
	Code             string     `gorm:"column:code;type:character varying(64);not null" json:"code"`
	Title            string     `gorm:"column:title;type:character varying(128);not null" json:"title"`
	Subtitle         *string    `gorm:"column:subtitle;type:character varying(128)" json:"subtitle"`
	Description      *string    `gorm:"column:description;type:character varying(512)" json:"description"`
	ImageURL         *string    `gorm:"column:image_url;type:character varying(512)" json:"image_url"`
	Background       *string    `gorm:"column:background;type:character varying(64)" json:"background"`
	ButtonText       *string    `gorm:"column:button_text;type:character varying(32)" json:"button_text"`
	TargetURL        *string    `gorm:"column:target_url;type:character varying(512)" json:"target_url"`
	AutoplaySeconds  *int32     `gorm:"column:autoplay_seconds;type:integer;not null;default:5" json:"autoplay_seconds"`
	StartsAt         *time.Time `gorm:"column:starts_at;type:timestamp without time zone;index:idx_carousel_slides_window,priority:1" json:"starts_at"`
	EndsAt           *time.Time `gorm:"column:ends_at;type:timestamp without time zone;index:idx_carousel_slides_window,priority:2" json:"ends_at"`
	VisibleRoleCodes *string    `gorm:"column:visible_role_codes;type:jsonb;not null;index:idx_carousel_slides_visible_role_codes,priority:1;default:[]" json:"visible_role_codes"`
	SortOrder        int32      `gorm:"column:sort_order;type:integer;not null;index:idx_carousel_slides_status_sort,priority:2" json:"sort_order"`
	Status           *int16     `gorm:"column:status;type:smallint;not null;index:idx_carousel_slides_status_sort,priority:3;default:1" json:"status"`
	CreatedBy        *int64     `gorm:"column:created_by;type:bigint" json:"created_by"`
	UpdatedBy        *int64     `gorm:"column:updated_by;type:bigint" json:"updated_by"`
	CreatedAt        *time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        *time.Time `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName CarouselSlide's table name
func (*CarouselSlide) TableName() string {
	return TableNameCarouselSlide
}
