// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQuickEntry = "quick_entries"

// QuickEntry mapped from table <quick_entries>
type QuickEntry struct {
	ID               int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:idx_quick_entries_status_sort,priority:1" json:"id"`
	Code             string     `gorm:"column:code;type:character varying(64);not null" json:"code"`
	Title            string     `gorm:"column:title;type:character varying(64);not null" json:"title"`
	IconURL          *string    `gorm:"column:icon_url;type:character varying(255)" json:"icon_url"`
	IconText         *string    `gorm:"column:icon_text;type:character varying(16)" json:"icon_text"`
	TargetURL        string     `gorm:"column:target_url;type:character varying(512);not null" json:"target_url"`
	Description      *string    `gorm:"column:description;type:character varying(255)" json:"description"`
	VisibleRoleCodes *string    `gorm:"column:visible_role_codes;type:jsonb;not null;index:idx_quick_entries_visible_role_codes,priority:1;default:[]" json:"visible_role_codes"`
	SortOrder        int32      `gorm:"column:sort_order;type:integer;not null;index:idx_quick_entries_status_sort,priority:2" json:"sort_order"`
	Status           *int16     `gorm:"column:status;type:smallint;not null;index:idx_quick_entries_status_sort,priority:3;default:1" json:"status"`
	CreatedBy        *int64     `gorm:"column:created_by;type:bigint" json:"created_by"`
	UpdatedBy        *int64     `gorm:"column:updated_by;type:bigint" json:"updated_by"`
	CreatedAt        *time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        *time.Time `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName QuickEntry's table name
func (*QuickEntry) TableName() string {
	return TableNameQuickEntry
}
