// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRecommendationItem = "recommendation_items"

// RecommendationItem mapped from table <recommendation_items>
type RecommendationItem struct {
	ID               int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_recommendation_items_status_sort,priority:1" json:"id"`
	ResourceID       *int64     `gorm:"column:resource_id;type:bigint;index:idx_recommendation_items_resource,priority:1" json:"resource_id"`
	Title            string     `gorm:"column:title;type:character varying(128);not null" json:"title"`
	Subtitle         *string    `gorm:"column:subtitle;type:character varying(128)" json:"subtitle"`
	SourceName       *string    `gorm:"column:source_name;type:character varying(64)" json:"source_name"`
	SourceURL        *string    `gorm:"column:source_url;type:character varying(512)" json:"source_url"`
	IconURL          *string    `gorm:"column:icon_url;type:character varying(255)" json:"icon_url"`
	IconText         *string    `gorm:"column:icon_text;type:character varying(16)" json:"icon_text"`
	TargetURL        *string    `gorm:"column:target_url;type:character varying(512)" json:"target_url"`
	PublishedAt      *time.Time `gorm:"column:published_at;type:timestamp without time zone;index:idx_recommendation_items_published_at,priority:1" json:"published_at"`
	VisibleRoleCodes *string    `gorm:"column:visible_role_codes;type:jsonb;not null;index:idx_recommendation_items_visible_role_codes,priority:1;default:[]" json:"visible_role_codes"`
	SortOrder        int32      `gorm:"column:sort_order;type:integer;not null;index:idx_recommendation_items_status_sort,priority:2" json:"sort_order"`
	Status           *int16     `gorm:"column:status;type:smallint;not null;index:idx_recommendation_items_status_sort,priority:3;default:1" json:"status"`
	CreatedBy        *int64     `gorm:"column:created_by;type:bigint" json:"created_by"`
	UpdatedBy        *int64     `gorm:"column:updated_by;type:bigint" json:"updated_by"`
	CreatedAt        *time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        *time.Time `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName RecommendationItem's table name
func (*RecommendationItem) TableName() string {
	return TableNameRecommendationItem
}
