// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameResource = "resources"

// Resource mapped from table <resources>
type Resource struct {
	ID            int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_resources_category_status_sort,priority:1;index:idx_resources_featured_sort,priority:1;index:idx_resources_status_sort,priority:1" json:"id"`
	CategoryID    *int32     `gorm:"column:category_id;type:integer;index:idx_resources_category_status_sort,priority:2" json:"category_id"`
	Slug          string     `gorm:"column:slug;type:character varying(128);not null" json:"slug"`
	Name          string     `gorm:"column:name;type:character varying(128);not null" json:"name"`
	IconURL       *string    `gorm:"column:icon_url;type:character varying(255)" json:"icon_url"`
	IconText      *string    `gorm:"column:icon_text;type:character varying(16)" json:"icon_text"`
	WebsiteURL    *string    `gorm:"column:website_url;type:character varying(512)" json:"website_url"`
	Summary       *string    `gorm:"column:summary;type:character varying(255)" json:"summary"`
	Description   *string    `gorm:"column:description;type:text" json:"description"`
	ResourceType  *string    `gorm:"column:resource_type;type:character varying(32);not null;default:tool" json:"resource_type"`
	Provider      *string    `gorm:"column:provider;type:character varying(128)" json:"provider"`
	ModelCount    int32      `gorm:"column:model_count;type:integer;not null" json:"model_count"`
	FollowerCount int32      `gorm:"column:follower_count;type:integer;not null" json:"follower_count"`
	Badge         *string    `gorm:"column:badge;type:character varying(32)" json:"badge"`
	Tags          *string    `gorm:"column:tags;type:jsonb;not null;index:idx_resources_tags,priority:1;default:[]" json:"tags"`
	Metadata      *string    `gorm:"column:metadata;type:jsonb;not null;default:{}" json:"metadata"`
	IsFeatured    bool       `gorm:"column:is_featured;type:boolean;not null;index:idx_resources_featured_sort,priority:2" json:"is_featured"`
	SortOrder     int32      `gorm:"column:sort_order;type:integer;not null;index:idx_resources_category_status_sort,priority:3;index:idx_resources_featured_sort,priority:3;index:idx_resources_status_sort,priority:2" json:"sort_order"`
	Status        *int16     `gorm:"column:status;type:smallint;not null;index:idx_resources_category_status_sort,priority:4;index:idx_resources_featured_sort,priority:4;index:idx_resources_status_sort,priority:3;default:1" json:"status"`
	CreatedBy     *int64     `gorm:"column:created_by;type:bigint" json:"created_by"`
	UpdatedBy     *int64     `gorm:"column:updated_by;type:bigint" json:"updated_by"`
	CreatedAt     *time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     *time.Time `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Resource's table name
func (*Resource) TableName() string {
	return TableNameResource
}
