// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameResourceCategory = "resource_categories"

// ResourceCategory mapped from table <resource_categories>
type ResourceCategory struct {
	ID          int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:idx_resource_categories_status_sort,priority:1" json:"id"`
	Code        string     `gorm:"column:code;type:character varying(64);not null" json:"code"`
	Name        string     `gorm:"column:name;type:character varying(64);not null" json:"name"`
	Description *string    `gorm:"column:description;type:character varying(255)" json:"description"`
	SortOrder   int32      `gorm:"column:sort_order;type:integer;not null;index:idx_resource_categories_status_sort,priority:2" json:"sort_order"`
	Status      *int16     `gorm:"column:status;type:smallint;not null;index:idx_resource_categories_status_sort,priority:3;default:1" json:"status"`
	CreatedBy   *int64     `gorm:"column:created_by;type:bigint" json:"created_by"`
	UpdatedBy   *int64     `gorm:"column:updated_by;type:bigint" json:"updated_by"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ResourceCategory's table name
func (*ResourceCategory) TableName() string {
	return TableNameResourceCategory
}
