// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID          int32   `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	Code        string  `gorm:"column:code;type:character varying(32);not null" json:"code"`
	Name        string  `gorm:"column:name;type:character varying(64);not null" json:"name"`
	Description *string `gorm:"column:description;type:character varying(255)" json:"description"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
