// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSearchHistory = "search_history"

// SearchHistory mapped from table <search_history>
type SearchHistory struct {
	ID              int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_search_history_user_recent,priority:1" json:"id"`
	UserID          int64      `gorm:"column:user_id;type:bigint;not null;index:idx_search_history_user_recent,priority:2" json:"user_id"`
	Query           string     `gorm:"column:query;type:character varying(128);not null" json:"query"`
	SearchCount     *int32     `gorm:"column:search_count;type:integer;not null;default:1" json:"search_count"`
	LastResultCount int32      `gorm:"column:last_result_count;type:integer;not null" json:"last_result_count"`
	LastSearchedAt  *time.Time `gorm:"column:last_searched_at;type:timestamp without time zone;not null;index:idx_search_history_user_recent,priority:3;default:CURRENT_TIMESTAMP" json:"last_searched_at"`
	CreatedAt       *time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       *time.Time `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName SearchHistory's table name
func (*SearchHistory) TableName() string {
	return TableNameSearchHistory
}
