// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserRole = "user_role"

// UserRole mapped from table <user_role>
type UserRole struct {
	UserID int64 `gorm:"column:user_id;type:bigint;primaryKey;index:idx_user_role_user_id,priority:1" json:"user_id"`
	RoleID int32 `gorm:"column:role_id;type:integer;primaryKey;index:idx_role,priority:1;index:idx_user_role_role_id,priority:1" json:"role_id"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
