// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID          int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:Primary Key" json:"id"`                                                                                  // Primary Key
	KeycloakID  string     `gorm:"column:keycloak_id;type:character varying(64);not null;comment:Keycloak UUID (sub)" json:"keycloak_id"`                                                              // Keycloak UUID (sub)
	Username    string     `gorm:"column:username;type:character varying(64);not null;comment:Username" json:"username"`                                                                               // Username
	Email       *string    `gorm:"column:email;type:character varying(128);index:idx_email,priority:1;index:idx_user_email,priority:1;comment:Email" json:"email"`                                     // Email
	Nickname    *string    `gorm:"column:nickname;type:character varying(64);comment:Nickname" json:"nickname"`                                                                                        // Nickname
	Avatar      *string    `gorm:"column:avatar;type:character varying(255);comment:Avatar" json:"avatar"`                                                                                             // Avatar
	Status      *int16     `gorm:"column:status;type:smallint;not null;index:idx_user_status,priority:1;default:1;comment:1=Active, 0=Disabled" json:"status"`                                         // 1=Active, 0=Disabled
	LastLoginAt *time.Time `gorm:"column:last_login_at;type:timestamp without time zone;comment:Last login time" json:"last_login_at"`                                                                 // Last login time
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;index:idx_user_created_at,priority:1;default:CURRENT_TIMESTAMP;comment:Creation time" json:"created_at"` // Creation time
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP;comment:Last update time" json:"updated_at"`                                   // Last update time
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
