// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserCommonTool = "user_common_tools"

// UserCommonTool mapped from table <user_common_tools>
type UserCommonTool struct {
	UserID     int64      `gorm:"column:user_id;type:bigint;primaryKey;index:idx_user_common_tools_user_sort,priority:1" json:"user_id"`
	ResourceID int64      `gorm:"column:resource_id;type:bigint;primaryKey;index:idx_user_common_tools_resource,priority:1" json:"resource_id"`
	SortOrder  int32      `gorm:"column:sort_order;type:integer;not null;index:idx_user_common_tools_user_sort,priority:2" json:"sort_order"`
	CreatedAt  *time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;index:idx_user_common_tools_user_sort,priority:3;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName UserCommonTool's table name
func (*UserCommonTool) TableName() string {
	return TableNameUserCommonTool
}
